### ISSUE TITLE
Duration Change always called twice

### ISSUE THREAD

**Issue by TheFrankman** [sharpstream/iono-playground#13]
```
player.on("durationchange", () => {
                // Event: duration change always called twice
                console.log('duration changed');
            });
```

**Comment by leonnortje** [comment]
It seems we fire the `durationchange` event when:

(a) the playlist item is loaded, from it's "duration" metadata
(b) the actual audio is loaded, from it's duration as reported from the browser.

We will fix this and document the expected behaviour better.

**Comment by mbalandis** [comment]
From the looks of it is fixed (or it is how it suppose to be)
