### ISSUE TITLE
Enabling preload causes playlists not to work

### ISSUE THREAD

**Issue by TheFrankman** [sharpstream/iono-playground#15]
Is this functionality ready yet ?

**Comment by leonnortje** [comment]
We have not really tested "preload" at all as we never use in our public player.

(The biggest reason being that it can cause a huge amount of content load from our servers which is never used. For example, we have customers embedding our player on their front-pages that receives 10m+ monthly pageviews, of which only a small fraction will be someone that actually listens to the content)

We are look into supporting this for you properly though and checking that all behaviour is as expected when using this flag.

**Comment by mbalandis** [comment]
Did some tests, looks like it is working! I will reopen if I get issues.
